// Generated by LiveScript 1.2.0
var main;
main = function($scope, $http){
  $scope.hash = [];
  $scope.change = function(){
    var hash, sentence, count, comma, i$, i, b, idx, cidx;
    hash = $scope.hash;
    sentence = [];
    count = 1;
    comma = ['，', '，', '；', '。', '。', '。'];
    for (i$ = 6; i$ <= 99; ++i$) {
      i = i$;
      if (!hash[i]) {
        continue;
      }
      b = hash[i];
      idx = parseInt(Math.random() * b.length);
      sentence.push(b[idx]);
      cidx = parseInt(Math.random() * count);
      if (cidx > 3) {
        count = 1;
      } else {
        count++;
      }
      if (i === 99) {
        cidx = comma.length - 1;
      }
      sentence.push(comma[cidx]);
    }
    return $scope.content = sentence.join("");
  };
  return $http.get('sentence-stat.json').success(function(hash){
    $scope.hash = hash;
    return $scope.change();
  });
};